### ISSUE TITLE
postgres service needs DB name specified

### ISSUE THREAD

**Issue by seanhoughton** [puppetlabs/puppet-in-docker-examples#11]
https://github.com/puppetlabs/puppet-in-docker-examples/blob/master/compose/docker-compose.yml

Without the DB name specified the default database is "postgres". The puppetdb is hardcoded to use "puppetdb" as the database name.

```
environment:
        - POSTGRES_PASSWORD=thepassword
        - POSTGRES_USER=theusername
        - POSTGRES_DB=puppetdb
```

**Comment by stahnma** [comment]
I didn't have that issue when I ran `docker-compose`. It looks like the migrations on start up take care of that. Is this still happening for you?

**Comment by underscorgan** [comment]
Thanks for the report, and apologies that it wasn't reviewed more quickly.

I was also unable to replicate this, so I'm going to close this issue, but please let us know if you're still having issues. We're in the process of migrating from GitHub issues to tickets on the Puppet JIRA (tickets.puppet.com), so if this is still an issue can you open a ticket in the CPR project (https://tickets.puppet.com/browse/CPR) with the 'Container' component?
