### ISSUE TITLE
Puppetboard & PuppetExplorer not compatible with PuppetDB4

### ISSUE THREAD

**Issue by mholttech** [puppetlabs/puppet-in-docker-examples#2]
Hi,

I'm trying out the docker-compose setup documented here and everything is working except Puppetboard and PuppetExplorer, both state that they only work with PuppetDB v3 but it looks like the PuppetDB image is running v4.  Is it possible to change this to v3?

**Comment by garethr** [comment]
@mholttech mmm, odd. Could you explain a bit more about what you mean by not working? Some screenshots or log output would be useful.

**Comment by garethr** [comment]
Hi @mholttech. I'm happy to look into this if you have output that will help me recreate it? Please reopen the issue if you have chance to provide more details.
