### ISSUE TITLE
PuppetDB will not speak with nodes or master.

### ISSUE THREAD

**Issue by blandman** [puppetlabs/puppet-in-docker-examples#3]
I've used the docker-compose script here: https://github.com/puppetlabs/puppet-in-docker-examples/tree/master/compose

The Puppetserver works like a champ, my nodes are checking in, and I was able to dump my code folder in as a volume with great success. 

However, I'm trying to setup PuppetDB for some specific automation I have in mind, and am running into the same problem I did on 3rd party docker images. I've tried multiple puppetdb images from different repositories, and initially I thought it was a problem with one of them, but I am having the same issue with this image too.

The puppetdb server starts and appears to run normally. I can make curl requests to the puppetdb instance, and I get responses, but none of my nodes or my master can utilize puppetdb with the puppet service. In the puppetdb logs I see the GET requests that I make manually, but nothing when the puppet master/agents attempt to query.

On any node after  `puppet agent --test`, this is what I get.

```
Warning: Unable to fetch my node definition, but the agent run will continue:
Warning: Error 400 on SERVER: Could not retrieve facts for vmnocnmnagios01: Failed to find facts from PuppetDB at puppet:8140: Failed to execute '/pdb/query/v4/nodes/vmnocnmnagios01/facts' on at least 1 of the following 'server_urls': https://puppetdb.psd401.net
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to execute '/pdb/cmd/v1?checksum=78d3d9242e4aa081b1cd35d419026569aa556090&version=4&certname=vmnocnmnagios01&command=replace_facts' on at least 1 of the following 'server_urls': https://puppetdb.psd401.net
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

When I try to run `puppet node status nodename` I get this

```
Error: Could not retrieve status for nodename: Failed to find '/pdb/query/v4/nodes/nodename' on any of the following 'server_urls': https://puppetdb.psd401.net
```

However if I run `curl https://puppetdb.psd401.net/pdb/query/v4/nodes/nodename` I get

```
{
  "error" : "No information is known about node nodename"
}
```

I've added the following to my site.pp on my master, then applied the site.pp to my master using `puppet apply /etc/puppetlabs/code/environments/production/manifests/site.pp`

```
node 'puppet' {
        class { 'puppetdb::master::config':
                puppetdb_server => 'puppetdb.psd401.net',
                puppetdb_port   => 443,
        }
}

node 'puppetdb' {
        class { 'puppetdb::server': }
}
```

(note dns for puppetdb is behind a load balancer for ssl)

I've tried many different network setups, from direct IP/port to the puppetdb, and through my load balancer with always the same result. Since the logs tell nothing, I am at a loss on where to search for solutions.

**Comment by garethr** [comment]
Hi @blandman 

The issue here is that the images assume PuppetDB is available at `puppetdb`, but it looks like your network configuration is prepending a host ie. `puppetdb.psd401.net`.

To work around that you can pass an environment variable to the `puppetserver` container, and also link the PuppetDB container up with the full host alias (or change it's name).

```yaml
environment:
    - PUPPETDB_SERVER_URLS=https://puppetdb.psd401.net:8081
links:
    - puppetdb:puppetdb.psd401.net
```

I'll look to get this documented too.

Out of interest what platform are you running on and what version of docker?

**Comment by henrydobson** [comment]
I think the problem goes further... I have run the compose network as a basic test and found that the master is unable to post to the puppetdb. 
```
WARN  [puppetserver] Puppet Error connecting to puppetdb on 8081 at route /pdb/cmd/v1?checksum=5f651c960fb4394e2b0f2ef6c995f320bba155aa&version=7&certname=1fb608eb0573.localdomain&command=store_report, error message received was 'Error executing http request'. Failing over to the next PuppetDB server_url in the 'server_urls' list
puppet
ERROR [puppetserver] Puppet Failed to execute '/pdb/cmd/v1?checksum=5f651c960fb4394e2b0f2ef6c995f320bba155aa&version=7&certname=1fb608eb0573.localdomain&command=store_report' on at least 1 of the following 'server_urls': https://puppetdb:8081
```
The containers are quite happily discovering each other with no issues and nodes are able to talk to puppet. Puppet just fails to store reports in puppetdb.

**Comment by garethr** [comment]
@henrydobson is this running compose with or without specifying the environment and explicit link as above?

**Comment by henrydobson** [comment]
With. I tried puppetdb.localdomain as well to account for the Ubuntu default which seems to be different from macOS. 

I'll run through them all again now.

**Comment by garethr** [comment]
If you could provide lots of information I'm happy to help try and debug:

1. Gist the full error output
2. Include the command you run to get the error
3. Include the full compose file you're running
4. Include the version of docker (you just provided the compose version above)

Using the compose setup is probably the easiest way of recreating.

Note that the easiest way of triggering the error is likely:

    docker run --net compose_default puppet/puppet-agent-alpine

Something else just came to mind. Do you mean you're seeing a non-crashing error during the initial compose run? If so that's completely fine, it's just part of the bootstrapping process.

1. PuppetDB needs to run Puppet against the Puppet Server in order to get a certificate
2. This causes Puppet Server to try and talk to PuppetDB (which obviously isn't configured and running yet)
3. Puppet Server is therefore configured to soft fail when it can't communicate with the PuppetDB instance

**Comment by henrydobson** [comment]
Ubuntu 14.04 host
docker-compose version 1.7.1, build 6c29830
Docker version 1.11.2, build b9f10c9

Repo: puppetlabs/puppet-in-docker-examples, Commit e4cfc659ef9ef39a20d1e2983b704d8846eb1888
Docker compose output including puppetserver errors: 
https://gist.github.com/henrydobson/2d17240e451409093ed721cc07a2d49e

Node output:
https://gist.github.com/henrydobson/c762a67bb4cc45f52e9aa896754d656b

**I found this worked:**
Repo: henrydobson/puppet-in-docker-examples, Commit 051ab158a5f824294b919e4e7f2dedb8ac07d583

**Comment by garethr** [comment]
@henrydobson ah, excellent. Glad you've got it working with passing PUPPETDB_SERVER_URLS and the link. I'll leave this issue open until I get some chance to document the various options.

**Comment by blandman** [comment]
CentOS Linux release 7.2.1511, Host
docker-compose version 1.7.1, build 0a9ab35
Docker version 1.12.0-rc2, build 906eacd

Repo: puppetlabs/puppet-in-docker-examples, Commit [d463b33](https://github.com/puppetlabs/puppet-in-docker-examples/commit/d463b33b281ddcc041cd9be81eb2191e823aa6e8)

Docker compose logs with puppetdb requests: https://gist.github.com/blandman/a80b6082578feb261d89590f407b2d3f

I'm seeing this in the logs: `Error 400 on SERVER: The environment must be purely alphanumeric, not 'puppet-ca'` However I'm not sure how this environment variable can be changed. 

I have another service on this host that is using port 8080/8081, so puppetdb can't. Here is my complete compose file: https://gist.github.com/blandman/0ede97e0ee65adf6259c45bed3cc8fb5

Since the SSL is trying to generate a key on our old dns (peninsula.wednet.edu), I have added a DNS entry for puppetdb and attempted to use that with no luck.

**Comment by blandman** [comment]
I realized what that 400 error was from, puppetdb could not reach my puppet master. I've corrected this in my docker-compose.yml, and upon creation the puppetdb server contacts the master and gets it's manifest. The problem however is the master is configured for puppetdb, but puppetdb can't reach itself and crashes the container with an exit code. Now I have to disable PuppetDB on the master so puppetdb can boot.

This feels so backwards and wrong. Which came first? Chicken or the Egg? Puppet Master or PuppetDB?

**Comment by v1v** [comment]
Maybe https://docs.docker.com/compose/compose-file/#/dependson might help to, or likely using the wait for script as suggested:
- https://docs.docker.com/compose/startup-order/

**Comment by luckyraul** [comment]
Hi, I have the very same issue. 

Containers have network domain name set by docker ( ```hostingname.club``` )

the @garethr suggested configuration fix is not helping, puppet server can't connect to ```puppetdb.hostingname.club```

with 

```
environment:
    - PUPPETDB_SERVER_URLS=https://puppetdb.hostingname.club:8081
links:
    - puppetdb:puppetdb.hostingname.club
```

**Comment by blandman** [comment]
I was able to get around these issue using compose' `extra_hosts` to forcefully direct puppetdb requests to the correct container. I couldn't use links because puppetdb was already linked to the master. Biggest issue is if the container's IP changes, I have to update the compose file.

**Comment by kirkins** [comment]
Was able to get this working locally. But it's causing issues deploying on docker cloud, as the puppetdb url changes every time I deploy.

**Comment by kirkins** [comment]
I noticed that when I use `puppet cert -la` I get back:

    "puppet.4c344086-a509-4b87-8ef3-4a13bea64bdb.local.dockerapp.io"   (SHA256) 27:92:60:A7:1D:F7:4D:47:EC:0D:B2:54:9B:B7:C7:8F:CE:9D:C8:00:E2:0F:8D:21:B3:0B:4A:D6:09:9C:CC:6F (alt names: "DNS:puppet", "DNS:puppet.4c344086-a509-4b87-8ef3-4a13bea64bdb.local.dockerapp.io")   

    "puppetdb.82f1f285-2624-47d6-bbc8-84a79ac621a1.local.dockerapp.io" (SHA256) 9E:1F:C0:28:0E:87:33:D1:21:1D:36:49:DE:7F:3F:66:DF:25:6F:CA:5E:09:6B:44:5D:AE:50:0F:95:5B:A8:A0 

The puppet server cert has an `alt name` attribute but puppetdb doesn't. I'm wondering if this could help with the connection issue.

**Comment by kirkins** [comment]
I was able to fix my issue mentioned above by deploying a custom image of puppetdb where the following line is changed:

https://github.com/puppetlabs/puppet-in-docker/blob/master/puppetdb/docker-entrypoint.sh#L8

Replacing `${HOSTNAME}` with `puppetdb`.

**Comment by underscorgan** [comment]
We're in the process of migrating from GitHub issues to the Puppet JIRA (tickets.puppet.com), so I've recreated this ticket (and included all of the comments from here) at https://tickets.puppetlabs.com/browse/CPR-580

I think a solution for this issue will be some parts documentation and some parts exposing additional configurations, but that work will be tracked off the linked ticket above (and any linked tickets for there).

Thanks all for all of the detailed information!
