### ISSUE TITLE
Photon Vagrantfile Bug

### ISSUE THREAD

**Issue by pizzaops** [puppetlabs/puppet-in-docker-examples#8]
I've been toying with the PhotonOS demo today from your puppet in docker repo, and it's failing to complete vagrant up pretty consistently for me.

It looks like it fails at this stage — `docker run $FLAGS -v /tmp/puppet:/var/puppet puppet/puppet-agent apply /var/puppet/manifests/init.pp --verbose` — because there is no `/var/puppet/manifests/init.pp` file.

It looks like you do in fact have a file provisioner in there to seed this, and it's before the command in question is run, but it's failing for some reason:

```
==> default: 2016-10-15
==> default: 00:06:14.600508
==> default: WARN
==> default:  puppetlabs.facter
==> default:  - Could not initialize locale, even with LC_* variables cleared. Continuing without localization support
==> default: Error: Could not run: Could not find file /var/puppet/manifests/init.pp
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

Digging into the `Vagrantfile` further:

`config.vm.provision "file", source: "manifests", destination: "/tmp/puppet"`

So it's copying the contents of `$PWD/manifests` to `/tmp/puppet`, resulting in `/tmp/puppet/init.pp` on the Photon system.

Then `/tmp/puppet` is mounted as a volume in the nginx container at `/var/puppet`.

So the manifest in question ends up as `/var/puppet/init.pp`, but puppet is trying to apply `/var/puppet/manifests/init.pp`.

PR inbound shortly.

**Comment by pizzaops** [comment]
@garethr PR #9

**Comment by underscorgan** [comment]
Closing this since https://github.com/puppetlabs/puppet-in-docker-examples/pull/9 was merged
